markdown: kramdown
permalink: /:title/
url: http://www.zozhou.net
name: zozhou
description: 用键盘敲下零碎的思绪
author: zozhou
email: scar1993@vip.qq.com
duoshuo: zozhou
#weibo: 1891858481
hub: zsc1993916
safe: true
paginate: 100
about: "用键盘敲下零碎的思绪"
