# Site Info
title: zozhou
tagline: ' 重重的壳裹着轻轻的仰望 '
description: ' 简单，纯粹 '
baseurl: ""
url: http://www.zozhou.net
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

auto_ids: true
footnote_nr: 1
entity_output: as_char
toc_levels: 1..6
smart_quotes: lsquo,rsquo,ldquo,rdquo

titlecase: false

version: 1.0.0

# About/contact
author:
  name: zozhou
  description: <script type="text/javascript" src="http://keleyi.com/keleyi/pmedia/jquery/jquery-1.11.1.min.js"></script>
<link href="http://keleyi.com/jq/myslider/css/jquery.myslider.0.1.3.css" type="text/css" rel="Stylesheet" />
<script type="text/javascript" src="http://keleyi.com/jq/myslider/js/jquery.myslider.0.1.3.js"></script>
<div id="myslider_keleyi_com" class="keleyimyslider">
<ul>
<li>This is a myslider demo.
</li>
<li><a href="http://keleyi.com/jq/myslider/">myslider home</a></li>
<li><a href="http://keleyi.com/">Keleyi Home</a></li>
<li><a href="http://keleyi.com/keleyi/">Keleyi Menu Home</a></li>
<li><a href="http://plugins.jquery.com/myslider/">jquery plugin myslider</a></li>
<li>
http://keleyi.com/jq/myslider/ </li>
</ul>
</div>

<script type="text/javascript">
$("#myslider_keleyi_com").myslider({ "width": "500px"
, "millisec": "2000"
, "animatespeed": 800
, "fontSize": "20px"
, "li_style": {"font-size":"20px"}
});
</script>, learning to be a giant.
  gravatar: 5a2f4adf358d3309865355ca74e49838 # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/zhoushch
    github:    https://github.com/zsc1993916
    # facebook:  <hide>
    email:     mailto:zhoushunchao93@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - 'https://github.com/zsc1993916/zsc1993916.github.io'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/home2.jpg
  caption: 我要一步一步往上爬，在最高点乘着叶片往前飞

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'zozhou' # leave blank if you don't want disqus

